(* generated by dune *)

(** @canonical Poker_odds_calculator.Card *)
module Card = Poker_odds_calculator__Card

(** @canonical Poker_odds_calculator.Equity_calculator *)
module Equity_calculator = Poker_odds_calculator__Equity_calculator

(** @canonical Poker_odds_calculator.Gui *)
module Gui = Poker_odds_calculator__Gui

(** @canonical Poker_odds_calculator.Hand_evaluator *)
module Hand_evaluator = Poker_odds_calculator__Hand_evaluator
